"""The ``@command`` decorator: registration for console (``:...``) commands.

Mirrors :mod:`miniagent.tools.registry`'s shape and for the same reason:
adding a command used to mean editing the console loop's if/elif chain,
``_print_help``, and the startup banner's hand-written command list —  three
places that already drifted. A command is now one function, decorated with
:func:`command`, and ``:help`` and the banner are both generated by walking
this registry instead of being maintained by hand.

Unlike a tool, a command needs no JSON schema — its one argument is whatever
raw text followed the command word — so this registry is smaller than the
tool one: just a name, its aliases, the handler, and the docstring used
verbatim as its help text.
"""

from __future__ import annotations

import inspect

# Canonical name -> CommandSpec, in registration order.
_REGISTRY: dict = {}

# Alias -> canonical name.
_ALIASES: dict = {}


class QuitLoop:
    """Sentinel a handler returns to tell the console loop to exit.

    Kept as a plain sentinel object rather than raising ``SystemExit``:
    ``runner.py`` deliberately blocks termination constructs, and a command
    handler is ordinary application code, not a special case.
    """

    def __repr__(self):
        return "QUIT"


#: Returned by the ``:quit``/``:q``/``:exit`` handler; checked by the loop.
QUIT = QuitLoop()


class CommandSpec:
    """One registered command: its name, aliases, handler and help text."""

    def __init__(self, name: str, func, aliases=()):
        self.name = name
        self.aliases = tuple(aliases)
        self.func = func
        self.help = inspect.cleandoc(func.__doc__ or "").strip()

    @property
    def names(self):
        """Every spelling that dispatches to this command, canonical first."""
        return (self.name,) + self.aliases

    def __call__(self, ctx, arg):
        return self.func(ctx, arg)


def command(name: str, aliases=()):
    """Decorator: register *func* as the handler for ``:name``.

    ``aliases`` are alternate spellings that dispatch to the same handler
    (``:q``/``:exit`` for ``:quit``, ``:models`` for ``:model``). The
    handler's signature is ``func(ctx, arg)``: *ctx* is the live
    :class:`~miniagent.context.Context`, *arg* is the raw text after the
    command word (``""`` when none was given). Its docstring becomes the
    command's ``:help`` entry verbatim, so it should be written the way it
    is meant to be read there.

    Registering a name or alias that collides with an existing command or
    alias raises immediately — at import time, not at first use — the same
    way a duplicate tool name does in :mod:`miniagent.tools.registry`.
    """

    def decorate(func):
        spec = CommandSpec(name, func, aliases=aliases)
        for taken in spec.names:
            if taken in _REGISTRY or taken in _ALIASES:
                raise ValueError(
                    f"command name/alias {taken!r} is already registered"
                )
        _REGISTRY[spec.name] = spec
        for alias in spec.aliases:
            _ALIASES[alias] = spec.name
        return spec

    return decorate


def get_spec(word: str):
    """Return the ``CommandSpec`` for *word* (no leading ``:``), or ``None``.

    *word* may be a canonical name or any registered alias.
    """
    canonical = _ALIASES.get(word, word)
    return _REGISTRY.get(canonical)


def all_specs():
    """Every registered command, in registration order."""
    return list(_REGISTRY.values())


def render_help() -> str:
    """The ``:help`` text, generated from every registered command's
    docstring.  Replaces a hand-maintained ``_print_help`` that had to be
    kept in sync with the dispatch logic by hand.
    """
    entries = []
    for spec in all_specs():
        heading = ", ".join(f":{n}" for n in spec.names)
        body = "\n".join("    " + line if line else "" for line in spec.help.splitlines())
        entries.append(heading + "\n" + body if body else heading)
    return "Commands\n\n" + "\n\n".join(entries)


def render_command_list(width: int = 54) -> str:
    """A word-wrapped list of every command (and its aliases), for the
    startup banner.  Generated the same way as :func:`render_help`, so the
    banner cannot list a command that no longer exists or omit one that was
    just added.
    """
    tokens = ["/".join(f":{n}" for n in spec.names) for spec in all_specs()]
    lines: list = []
    current: list = []
    current_len = 0
    for token in tokens:
        added = len(token) + (2 if current else 0)
        if current and current_len + added > width:
            lines.append("  " + "  ".join(current))
            current, current_len = [], 0
            added = len(token)
        current.append(token)
        current_len += added
    if current:
        lines.append("  " + "  ".join(current))
    return "\n".join(lines)
